#!/usr/bin/env python3
"""Render generated regions from routing.json + skills-manifest.json into docs.

Every fenced region marked with BEGIN/END GENERATED is rewritten in place from
the single sources of truth, so diagrams, listings, and data tables can never
drift from skill content. Human narrative outside the fences is preserved.

Usage:
    python scripts/render-skills.py            # render all regions in place
    python scripts/render-skills.py --check    # fail if any region is stale
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AGENT_DIR = ROOT / ".agent"
MANIFEST_PATH = AGENT_DIR / "shared" / "skills-manifest.json"
ROUTING_PATH = AGENT_DIR / "shared" / "routing.json"

CATEGORY_LABELS = {
    "core-workflow": "Core Workflow",
    "domain-expert": "Domain Expert",
    "meta-learning": "Meta & Learning",
    "token-optimization": "Token Optimization",
}
CATEGORY_PURPOSE = {
    "core-workflow": "Disciplined development practices: planning, execution, review, verification",
    "domain-expert": "Specialized technical expertise across architecture, DevOps, data, security",
    "meta-learning": "Efficiency and continuous improvement loops",
    "token-optimization": "Token reduction and context management",
}
AGENT_CATEGORIES = {
    "Development": ["tech-lead", "planner", "architect"],
    "Quality & Testing": ["code-reviewer", "qa-engineer", "accessibility-auditor", "adversarial-tester"],
    "Security & Compliance": ["security-reviewer", "data-privacy-officer"],
    "Operations & Releases": ["incident-commander", "release-manager"],
}

REGION_START = "<!-- BEGIN GENERATED: {region} -->"
REGION_END = "<!-- END GENERATED: {region} -->"
GENERATED_NOTE = "<!-- Generated by scripts/render-skills.py — DO NOT EDIT BY HAND -->"


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def first_sentence(desc: str) -> str:
    """Short one-line summary from a multi-sentence description."""
    clean = " ".join(desc.split())
    cut = re.search(r"\.\s+", clean)
    return clean[: cut.start() + 1] if cut else clean


# --------------------------------------------------------------------------
# Renderers
# --------------------------------------------------------------------------


def render_routing_matrix(manifest: dict, routing: dict) -> str:
    """ASCII request-type mapping, grouped by target skill category."""
    agents = sorted(r["skill"] for r in routing["routes"] if r["kind"] == "agent")
    by_cat = {c: [] for c in manifest["categories"]}
    by_cat["agents"] = []
    for route in sorted(routing["routes"], key=lambda r: (r["skill"], r["phrases"][0])):
        if route["kind"] == "agent":
            by_cat["agents"].append(route)
        else:
            target = next(
                (s for s in manifest["skills"] if s["name"] == route["skill"]), None
            )
            by_cat[target["category"] if target else "agents"].append(route)

    sections = []
    for cat, routes in by_cat.items():
        if not routes:
            continue
        label = "AGENTS" if cat == "agents" else CATEGORY_LABELS[cat].upper()
        rows = [f"  {label}"]
        for route in routes:
            phrases = " / ".join(f'"{p}"' for p in route["phrases"])
            target = route["skill"]
            if route["kind"] == "agent":
                target += " (agent)"
            rows.append(f"  ├── {phrases:<44}→ {target}")
        sections.append("\n".join(rows))

    width = max(len(line) for section in sections for line in section.splitlines()) + 2
    border = "┌" + "─" * width + "┐"
    bottom = "└" + "─" * width + "┘"
    body = "\n".join(
        line + " " * (width - len(line)) + "│" for section in sections for line in section.splitlines()
    )
    ascii_box = f"{border}\n{body}\n{bottom}"
    return f"```\n{ascii_box}\n```"


def render_skills_listing(manifest: dict, _routing: dict) -> str:
    """The /mega-mind skills command output."""
    agent_names = sorted(
        name for names in AGENT_CATEGORIES.values() for name in names
    )
    lines = [
        f"📚 Available Skills ({manifest['skill_count']} Active)",
        "━" * 44,
    ]
    for cat, names in manifest["categories"].items():
        lines.append(f"{CATEGORY_LABELS[cat].upper()} ({len(names)}): " + " · ".join(names))
    lines.append(f"AGENTS ({len(agent_names)}): " + " · ".join(agent_names))
    return "```\n" + "\n".join(lines) + "\n```"


def render_workflow_chains(manifest: dict, routing: dict) -> str:
    rows = ["| Chain | Steps |", "| --- | --- |"]
    for chain in routing["chains"]:
        steps = " → ".join(chain["steps"])
        rows.append(f"| {chain['name']} | `{steps}` |")
    return "\n".join(rows)


def render_skill_inventory(manifest: dict, _routing: dict) -> str:
    blocks = []
    for cat, names in manifest["categories"].items():
        label = CATEGORY_LABELS[cat]
        rows = ["| Skill | Description |", "| --- | --- |"]
        for name in names:
            entry = next(s for s in manifest["skills"] if s["name"] == name)
            rows.append(f"| `{name}` | {first_sentence(entry['description'])} |")
        blocks.append(f"### {label} ({len(names)})\n\n" + "\n".join(rows))
    return "\n\n".join(blocks)


def render_reference_skills(manifest: dict, _routing: dict) -> str:
    return render_skill_inventory(manifest, _routing)


def render_reference_chains(manifest: dict, routing: dict) -> str:
    return render_workflow_chains(manifest, routing)


def render_category_table(manifest: dict, _routing: dict) -> str:
    rows = ["| Category | Count | Purpose |", "| --- | --- | --- |"]
    for cat, names in manifest["categories"].items():
        rows.append(f"| {CATEGORY_LABELS[cat]} | {len(names)} | {CATEGORY_PURPOSE[cat]} |")
    rows.append(f"| **Total** | **{manifest['skill_count']}** | |")
    return "\n".join(rows)


# --------------------------------------------------------------------------
# Region plumbing
# --------------------------------------------------------------------------

REGIONS = [
    (AGENT_DIR / "skills" / "mega-mind" / "SKILL.md", "routing-matrix", render_routing_matrix),
    (AGENT_DIR / "skills" / "mega-mind" / "SKILL.md", "skills-listing", render_skills_listing),
    (ROOT / "README.md", "skill-inventory", render_skill_inventory),
    (ROOT / "docs-site" / "reference.md", "skills", render_reference_skills),
    (ROOT / "docs-site" / "reference.md", "chains", render_reference_chains),
    (ROOT / "docs-site" / "index.md", "category-table", render_category_table),
]

REGION_RE = re.compile(
    r"<!-- BEGIN GENERATED: ([a-z-]+) -->\n.*?<!-- END GENERATED: \1 -->\n?",
    re.DOTALL,
)


def render_region(region_id: str, manifest: dict, routing: dict) -> str:
    fn = next(f for _, rid, f in REGIONS if rid == region_id)
    return fn(manifest, routing)


def replace_region(text: str, region_id: str, content: str) -> str:
    block = f"{REGION_START.format(region=region_id)}\n{GENERATED_NOTE}\n{content}\n{REGION_END.format(region=region_id)}\n"
    start, end = REGION_START.format(region=region_id), REGION_END.format(region=region_id)
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end) + r"\n?", re.DOTALL)
    if pattern.search(text):
        return pattern.sub(block, text, count=1)
    return text + block  # region absent — append at end of file


def main() -> int:
    manifest = load_json(MANIFEST_PATH)
    routing = load_json(ROUTING_PATH)
    check = "--check" in sys.argv
    failures = []

    for path, region_id, _ in REGIONS:
        if not path.exists():
            if check:
                failures.append(f"{path.relative_to(ROOT)}: missing (region {region_id})")
            continue
        content = render_region(region_id, manifest, routing)
        text = path.read_text(encoding="utf-8")
        if check:
            # extract THIS region's fenced block (REGION_RE alone would match
            # the first generated block in the file, which may be another region)
            pattern = re.compile(
                re.escape(REGION_START.format(region=region_id))
                + r"\n.*?"
                + re.escape(REGION_END.format(region=region_id))
                + r"\n?",
                re.DOTALL,
            )
            m = pattern.search(text)
            existing_block = m.group(0) if m else ""
            rendered = replace_region("", region_id, content)
            if existing_block != rendered:
                failures.append(
                    f"{path.relative_to(ROOT)}: region '{region_id}' is stale — run `python scripts/render-skills.py`"
                )
        else:
            expected = replace_region(text, region_id, content)
            if text != expected:
                path.write_text(expected, encoding="utf-8")
                print(f"[UPDATED] {path.relative_to(ROOT)} (region {region_id})")

    if check:
        if failures:
            for f in failures:
                print(f"[STALE] {f}", file=sys.stderr)
            return 1
        print(f"[OK] all {len(REGIONS)} generated regions are fresh")
        return 0
    print("[OK] rendering complete")
    return 0


if __name__ == "__main__":
    sys.exit(main())
