#!/usr/bin/env python3
"""Mega-Mind Skill System Validator — manifest-driven.

Consumes .agent/shared/skills-manifest.json (generated by build-manifest.py) and
.agent/shared/routing.json (curated routing data). Checks, in order:

  1. skill_count      — manifest count vs AGENTS.md declared count
  2. manifest_fresh   — every SKILL.md's sha256 matches the committed manifest
  3. frontmatter      — name==dir, category valid, version semver, >=3 triggers
  4. gold_standard    — all 12 canonical sections present per the manifest
  5. routing          — every route target resolves; every skill covered
  6. trigger_collision— no two skills share a normalized trigger phrase
  7. chains           — every chain step resolves to a skill or agent
  8. version          — pyproject.toml == __init__.py fallback; spec version sane

Usage: python scripts/validate-skill-system.py [--report]
"""

import io
import json
import re
import sys
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent
AGENT_DIR = ROOT / ".agent"
SKILLS_DIR = AGENT_DIR / "skills"
MANIFEST_PATH = AGENT_DIR / "shared" / "skills-manifest.json"
ROUTING_PATH = AGENT_DIR / "shared" / "routing.json"
AGENTS_DIR = AGENT_DIR / "agents"
PYPROJECT_PATH = ROOT / "pyproject.toml"
INIT_PATH = ROOT / "src" / "mega_mind" / "__init__.py"

VALID_CATEGORIES = {
    "core-workflow",
    "domain-expert",
    "meta-learning",
    "token-optimization",
}


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def load_json(path: Path) -> dict:
    return json.loads(read(path))


def issue(sev: str, check: str, msg: str) -> dict:
    return {"sev": sev, "check": check, "msg": msg}


# ---------------------------------------------------------------------------
# Checks
# ---------------------------------------------------------------------------


def check_skill_count(manifest: dict) -> list[dict]:
    content = read(AGENT_DIR / "AGENTS.md")
    declared = None
    for m in re.finditer(r"(\d+)\s+(?:Active\s+)?skills?", content, re.IGNORECASE):
        declared = int(m.group(1))
    actual = manifest["skill_count"]
    if declared and declared != actual:
        return [issue("ERROR", "skill_count", f"AGENTS.md says {declared}, manifest has {actual}")]
    return [issue("OK", "skill_count", f"{actual} skills (AGENTS.md matches manifest)")]


def check_manifest_fresh(manifest: dict) -> list[dict]:
    import hashlib

    def norm_sha256(path: Path) -> str:
        data = path.read_bytes().replace(b"\r\n", b"\n")  # platform-independent
        return hashlib.sha256(data).hexdigest()

    stale = []
    for entry in manifest["skills"]:
        path = SKILLS_DIR / entry["name"] / "SKILL.md"
        if not path.exists():
            stale.append(f"{entry['name']}: SKILL.md missing on disk")
            continue
        if norm_sha256(path) != entry["sha256"]:
            stale.append(
                f"{entry['name']}: hash mismatch — run `python scripts/build-manifest.py`"
            )
    if stale:
        return [issue("ERROR", "manifest_fresh", "; ".join(stale))]
    return [issue("OK", "manifest_fresh", "all 53 SKILL.md hashes match the manifest")]


def check_frontmatter(manifest: dict) -> list[dict]:
    problems = []
    for entry in manifest["skills"]:
        name = entry["name"]
        if entry["category"] not in VALID_CATEGORIES:
            problems.append(f"{name}: invalid category '{entry['category']}'")
        if not re.match(r"^\d+\.\d+\.\d+$", entry["version"]):
            problems.append(f"{name}: non-semver version '{entry['version']}'")
        if len(entry["triggers"]) < 3:
            problems.append(f"{name}: only {len(entry['triggers'])} triggers (min 3)")
        if not entry["description"]:
            problems.append(f"{name}: empty description")
    if problems:
        return [issue("ERROR", "frontmatter", "; ".join(problems))]
    return [issue("OK", "frontmatter", "all frontmatter valid (category, version, triggers, description)")]


def check_gold_standard(manifest: dict) -> list[dict]:
    problems = []
    for entry in manifest["skills"]:
        missing = entry.get("missing_sections", [])
        if missing:
            problems.append(f"{entry['name']}: missing {', '.join(missing)}")
    if problems:
        return [issue("ERROR", "gold_standard", "; ".join(problems))]
    return [issue("OK", "gold_standard", "all 12 canonical sections present in all 53 skills")]


def check_routing(manifest: dict, routing: dict) -> list[dict]:
    skill_names = {s["name"] for s in manifest["skills"]}
    agent_names = {p.stem for p in AGENTS_DIR.glob("*.md")}
    real_targets = skill_names | agent_names
    exempt = set(manifest.get("routing_exempt", []))

    problems = []
    referenced = set()
    for route in routing["routes"]:
        target = route["skill"]
        referenced.add(target)
        if target not in real_targets:
            problems.append(f"route '{route['phrases'][0]}' -> unknown target '{target}'")

    for chain in routing["chains"]:
        referenced.update(chain["steps"])

    covered = referenced | exempt
    unrouted = sorted(skill_names - covered)
    if unrouted:
        problems.append(f"unrouted skills: {', '.join(unrouted)} (add to routing.json or routing_exempt)")

    if problems:
        return [issue("ERROR", "routing", "; ".join(problems))]
    return [issue("OK", "routing", f"all {len(routing['routes'])} routes resolve; {len(skill_names)} skills covered")]


def check_chains(manifest: dict, routing: dict) -> list[dict]:
    skill_names = {s["name"] for s in manifest["skills"]}
    agent_names = {p.stem for p in AGENTS_DIR.glob("*.md")}
    real_targets = skill_names | agent_names
    problems = []
    for chain in routing["chains"]:
        for step in chain["steps"]:
            if step not in real_targets:
                problems.append(f"chain '{chain['name']}': unknown step '{step}'")
    if problems:
        return [issue("ERROR", "chains", "; ".join(problems))]
    return [issue("OK", "chains", f"all {len(routing['chains'])} chains reference real skills/agents")]


# Generic terms that appear in many skills' triggers without implying a routing
# conflict (reported as noise rather than ambiguity).
TRIGGER_STOPWORDS = {
    "workflow",
    "workflows",
    "verify",
    "testing",
    "tests",
    "feature",
    "production",
}


def check_trigger_collision(manifest: dict) -> list[dict]:
    seen: dict[str, set[str]] = {}
    for entry in manifest["skills"]:
        for trigger in entry["triggers"]:
            norm = re.sub(r"[^a-z0-9]+", " ", trigger.lower()).strip()
            if len(norm) < 4 or norm in TRIGGER_STOPWORDS:
                continue
            seen.setdefault(norm, set()).add(entry["name"])
    # a trigger shared by two different skills is a routing ambiguity
    collisions = {k: v for k, v in seen.items() if len(v) > 1}
    if collisions:
        msg = "; ".join(f"'{k}' -> {', '.join(sorted(v))}" for k, v in sorted(collisions.items()))
        return [issue("WARNING", "trigger_collision", msg)]
    return [issue("OK", "trigger_collision", "no trigger collisions between skills")]


def check_skill_versions(manifest: dict) -> list[dict]:
    """Frontmatter version must equal the skill's own latest changelog row.

    A skill bumped in its Changelog but not in frontmatter (or vice versa)
    silently misreports its release level everywhere that reads frontmatter.
    """
    problems = []
    for entry in manifest["skills"]:
        txt = read(SKILLS_DIR / entry["name"] / "SKILL.md")
        chg = re.search(
            r"## Changelog\s*\n\|[^\n]*\n\|[^\n]*\n\|\s*([\d.]+)\s*\|", txt
        )
        latest = chg.group(1) if chg else None
        if latest and latest != entry["version"]:
            problems.append(
                f"{entry['name']}: frontmatter {entry['version']} != changelog {latest}"
            )
    if problems:
        return [issue("ERROR", "skill_versions", "; ".join(problems))]
    return [issue("OK", "skill_versions", "frontmatter version == latest changelog row for all 53 skills")]


def check_version() -> list[dict]:
    pyproject = read(PYPROJECT_PATH)
    init_src = read(INIT_PATH)
    py_v = re.search(r'^version\s*=\s*"([^"]+)"', pyproject, re.M)
    fallback = re.search(r'__version__ = "([^"]+)"', init_src)
    problems = []
    if not py_v:
        problems.append("pyproject.toml: version missing")
    elif fallback and py_v.group(1) != fallback.group(1):
        problems.append(
            f"version drift: pyproject.toml {py_v.group(1)} vs __init__.py fallback {fallback.group(1)}"
        )
    spec = read(AGENT_DIR / "shared" / "GOLD-STANDARD-SKILL.md")
    if "Template v2.0" not in spec:
        problems.append("GOLD-STANDARD-SKILL.md: header must read 'Template v2.0'")
    if problems:
        return [issue("ERROR", "version", "; ".join(problems))]
    return [issue("OK", "version", f"pyproject {py_v.group(1)} == __init__.py fallback; spec v2.0")]


def main() -> int:
    manifest = load_json(MANIFEST_PATH)
    routing = load_json(ROUTING_PATH)

    all_issues: list[dict] = []
    for check in [
        check_skill_count,
        lambda m: check_manifest_fresh(m),
        check_frontmatter,
        check_gold_standard,
        lambda m: check_skill_versions(m),
        lambda m: check_routing(m, routing),
        lambda m: check_chains(m, routing),
        check_trigger_collision,
        lambda m: check_version(),
    ]:
        all_issues.extend(check(manifest))

    errors = [i for i in all_issues if i["sev"] == "ERROR"]
    warnings = [i for i in all_issues if i["sev"] == "WARNING"]
    ok = [i for i in all_issues if i["sev"] == "OK"]

    print("=" * 60)
    print(f"Results: {len(errors)} errors, {len(warnings)} warnings, {len(ok)} passed")
    print("=" * 60)
    for i in all_issues:
        icon = {"ERROR": "X", "WARNING": "!", "OK": "+"}.get(i["sev"], "?")
        print(f"  [{icon}] [{i['check']}] {i['msg']}")

    if "--report" in sys.argv:
        from datetime import datetime

        rpath = AGENT_DIR / "evals" / "validation-report.md"
        lines = [
            "# Validation Report",
            f"Date: {datetime.now().isoformat()[:10]}",
            "",
            f"Errors: {len(errors)}",
            f"Warnings: {len(warnings)}",
            "",
        ]
        for i in all_issues:
            lines.append(f"- [{i['sev']}] {i['check']}: {i['msg']}")
        rpath.parent.mkdir(parents=True, exist_ok=True)
        rpath.write_text("\n".join(lines), encoding="utf-8")
        print(f"\nReport: {rpath.relative_to(ROOT)}")

    return 0 if len(errors) == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
